name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Або master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        # ЗАМІНІТЬ <repository-name> на назву вашого репозиторію!
        run: flutter build web --release --base-href "/LetterBoxWeb/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web